require 'rubygems'
require 'bundler/setup'
require 'rspec'
require 'capybara/rspec'
# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
Capybara.default_driver = :selenium
RSpec.configure do |config|
  config.include Capybara::DSL # just shotgun this since we aren't doing any other testing
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end
